.TH TTWM 1

.SH NAME
Alopex \- A Tabbed Tiling Window Manager

.SH SYNOPSIS
.B alopex

.SH DESCRIPTION
TODO

All keybindings are customizable by modifying config.h and recompiling.  The listings below are the default settings.

.SH KEY BINDINGS
TODO - man pages are under construction

.SH SEE ALSO
http://trilbywhite.github.com/ttwm

