.TH TTWM 1

.SH NAME
TTWM \- Tiny Tabbed/Tiler Window Manager

.SH SYNOPSIS
.B ttwm

.SH DESCRIPTION
ttwm is a lightweight tiling window manager with one master region and one stack region.  Only two windows are visible at any time, other windows are tabbed in the stack region.  The stack can be on the right or bottom of the screen.  Ttwm has workspaces, customizable key bindings, transient floating and fullscreen modes, and limited support for external monitors.

All keybindings are customizable by modifying config.h and recompiling.  The listings below are the default settings.

.SH KEY BINDINGS
TODO - man pages are under construction

.SH SEE ALSO
http://trilbywhite.github.com/ttwm

