#!/bin/bash

case "$1" in
	up)		amixer set Master 3%+		>/dev/null ;;
	down)	amixer set Master 3%-		>/dev/null ;;
	toggle)	amixer set Master toggle	>/dev/null ;;
	*)		exit ;;
esac

# Get the volume as a single number
amixer get Master | awk '
/Mono:/ { gsub(/[\[\]]/,"",$4); gsub(/%/,"",$4); print $4 }
' > ~/.audio_volume

# Check if muted; replace volume with "-1" if muted
[[ `amixer get Master | grep "Mono:.*\[off\]"` ]] &&
	echo "-1" > ~/.audio_volume

# vim: ts=4
