#!/bin/bash

icons=(tag cpu mem aud bat wfi clk)
[[ $# -gt 0 ]] && icons=($@)

cat <<'EOF' > icons.svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
	version="1.1"
	baseProfile="full"
	xmlns="http://www.w3.org/2000/svg"
	xmlns:xlink="http://www.w3.org/1999/xlink"
	xmlns:ev="http://www.w3.org/2001/xml-events"
	preserveAspectRatio="xMinYMin"
	viewBox="0 0 1600 1600">
EOF


let line=0

for opt in ${icons[@]}; do
	let row=line+1
	let y=line*160
	echo "<g id=\"row1\" transform=\"translate(0,$y)\">"
	cat ${opt}.svg
	echo "</g>"
	echo
	let line++
done >> icons.svg


echo "</svg>" >> icons.svg

convert icons.svg -alpha set -fuzz 24% -fill none -floodfill +0+0 white icons.png
rm icons.svg


